### PR TITLE
Add Estonian language support

### PR DESCRIPTION
**Pull request by LiivaneLord**
Estonian translation

### CODE REVIEW

**Comment by superdingo101** [comment]
Thank you for contributing this! 🎉 I really appreciate you taking the time to add Estonian support, and especially appreciate this being your first contribution to the project.

I reviewed the new translation block closely. Overall, this is a solid and impressively complete contribution: the `et` / `et-EE` locale setup is correct, the translation keys are complete, and important placeholders such as `{title}`, `{count}`, and `{time}` are preserved correctly.

Before I can merge it, I have a few requested changes.

## Must fix

### 1. Rebuild and commit the generated bundle

The PR updates `src/translations.js`, but the generated `skylight-calendar-card.js` bundle was not updated. This is why the **Tests** workflow is currently failing at **“Verify generated bundle is current.”**

Please rebuild the project and commit the resulting bundle change:

```
npm ci
npm run build
git add skylight-calendar-card.js
```

This is important because `skylight-calendar-card.js` is the actual distributed file loaded by HACS users.

### 2. Please revise the translations using `esinemine` for recurring-event occurrences

These four strings currently use `esinemine`:

```
editThisOccurrence: 'Muuda ainult seda esinemist',
editThisOccurrenceAndFuture: 'Muuda seda ja kõiki tulevasi esinemisi',
deleteThisOccurrence: 'Kustuta ainult see esinemine',
deleteThisOccurrenceAndFuture: 'Kustuta see ja tulevased esinemised',
```

My review indicates that `esinemine` refers more to a performance or public appearance and is misleading for one occurrence of a recurring calendar event.

I strongly suggest wording based on `kordus`, for example:

```
editThisOccurrence: 'Muuda ainult seda kordust',
editThisOccurrenceAndFuture: 'Muuda seda ja kõiki tulevasi kordusi',
deleteThisOccurrence: 'Kustuta ainult see kordus',
deleteThisOccurrenceAndFuture: 'Kustuta see ja kõik tulevased kordused',
```

If there is a more natural Estonian calendar-specific term you prefer, I am very open to that—the key point is that these options should clearly mean one instance of a recurring event.

## Strong recommendations

I also recommend addressing the following translation issues in this PR:

### Preserve the meaning of “Family Calendar”

Current:

```
defaultTitle: 'Kalender'
```

Suggested:

```
defaultTitle: 'Perekalender'
```

The English default is `Family Calendar`, so the current version drops part of the meaning.

### Preserve “weekly” in the weekday validation message

Current:

```
recurrenceSelectWeekday: 'Vali vähemalt üks nädalapäev korduvate sündmuste jaoks'
```

The English text specifically refers to **weekly recurring events**. Suggested wording:

```
recurrenceSelectWeekday: 'Vali iganädalase korduse jaoks vähemalt üks nädalapäev'
```

### Improve the Google Calendar grammatical forms

Current examples include:

```
googleCalendarLimitationTitle: 'ℹ️ Google Calendar piirang:'
```

and:

```
Kasuta Google Calendar rakendust või veebilehte.
```

I recommend:

```
googleCalendarLimitationTitle: 'ℹ️ Google Calendari piirang:'
```

and:

```
Kasuta Google Calendari rakendust või veebilehte.
```

Please apply the same correction to the similar Google Calendar error text.

### Consider more natural wording for these strings

Current:

```
recurrenceIntervalSuffix: 'intervall(i)'
```

Suggested:

```
recurrenceIntervalSuffix: 'intervall'
```

Current:

```
descriptionPlaceholder: 'Sündmuse detailid...'
```

Suggested:

```
descriptionPlaceholder: 'Sündmuse üksikasjad...'
```

These are recommendations rather than blockers if you feel the current wording is more natural as a native speaker.

## Repository housekeeping

A couple of additional items would help keep the contribution consistent with the project:

* Please update the supported-language documentation to include `et` / Estonian in:

  * `docs/faq.mdx`
  * `docs/configuration/basic.mdx`
* Please normalize the new translation block to the existing two-space indentation style instead of tabs.
* This repository normally develops through the `dev` branch and then merges `dev` into `main` for releases, so I will also want this PR targeted to `dev` rather than `main`.

Thanks again for making this contribution. Adding a full translation is a meaningful amount of work, and most of the translation set looks good. I especially appreciate that the full key set and runtime placeholders were handled correctly. Once the required items above are addressed, this will be a great addition to Daylight Calendar Card. 🙌

**Comment by LiivaneLord** [comment]
Hello

1. I'm very sorry. I had translated my Home Assistant interface into Estonian, but the recent update overwrote it. So I tried to do it again through GitHub.

As you can probably see, I'm a complete beginner at this, and my head was about to explode trying to figure out how everything works here. But I installed GitHub Desktop (and a few additional tools), and I think I can move forward from here now. 🙂

2. "esinemine" can also refer to a repetition within a pattern. However, I agree that "kordus" is the better choice in this context.

3. About "interval", something looks broken here. Is it only for me or others too?:
image

There should be row like: Repeat every [interval count] [day(s)/week(s)/month(s)/year(s)].

Actually, I think I should translate "interval(s)" as "tagant" since its shorter word or, if I want to preserve a similar concept then should use "intervalliga". I think the latter fits quite well, so I'll use "intervalliga" for now.

4. Other words I changed as you suggested. Also updated .mdx files. I will try to build it now. Wish me luck. :D

**Comment by superdingo101** [comment]
Thank you again — the Estonian translation changes look much better, and you addressed the translation feedback really well! 🙌

I changed the PR target to the correct `dev` branch. There are just two cleanup steps left:

### 1. Update your PR branch with the latest `dev`

On the main **Conversation** page of this pull request, scroll down to the merge/status box near the bottom and click **Update branch**.

This will bring the latest `dev` changes into your branch. Some translation keys currently shown in the PR already exist in `dev`, so updating the branch should clean those unrelated changes out of the PR diff.

### 2. Remove the accidental package dependency changes

Please restore these two files so they match the `dev` branch:

* `package.json`
* `package-lock.json`

The added `@rollup/rollup-win32-x64-msvc` dependency is Windows-specific and is causing both GitHub Actions workflows to fail on the Linux CI runner. No package dependency changes are needed for this translation.

After those changes are committed and pushed to the same `LiivaneLord-patch-1` branch, GitHub will automatically update this PR and rerun the checks.

No further translation changes are required from my review — the important translation feedback has been addressed. Thank you for working through this, especially on your first GitHub contribution!

**Comment by LiivaneLord** [comment]
Hi

Very complicated. I saw that only package-lock.json got update in my github program after I pulled updated branch in my github program.

I think I mess everything. :S

**Comment by LiivaneLord** [comment]
Hi

Do I have to rebuild bundle?

Previously when I ran:

npm ci
npm run build
git add skylight-calendar-card.js

I got error "Error: Cannot find module @rollup/rollup-win32-x64-msvc. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory."

From web I found that I should run:

npm install @rollup/rollup-win32-x64-msvc

after that commands succeeded.

**Comment by LiivaneLord** [comment]
Hi

I downloaded package.json and package-lock.json from your project and manually pasted these into github folder on my PC. 

I didnt understand why latest package.json didnt receive into my branch.

If it wont work then I give up. :(

**Comment by superdingo101** [comment]
Hi! Thank you for continuing to work on this — please pause and don’t make any more changes to this PR for now. 🙂

The earlier dependency failures exposed a separate cross-platform `package-lock.json` problem in the main repository. That is not an Estonian translation issue, and I’m working on fixing it separately in `dev`.

At this point, your PR looks good: the translation changes are isolated correctly and the checks are passing. More attempts to update dependencies or merge branches may accidentally reintroduce unrelated changes.

Please leave the PR as it is for now, and I’ll handle the remaining repository dependency work separately. Thank you again for your patience and for the translation contribution!

**Comment by LiivaneLord** [comment]
Yeah, I’m not touching it anymore. I feel like I’ve finally earned myself a shot of vodka after this.

If anything, I should be thanking you for your patience throughout all of this. I sincerely hope I didn’t mess anything up.

**Comment by superdingo101** [comment]
No no, don't beat yourself up! I am very thankful for your contributions! And so happy to see this simple project used around the world 😀 you got the translations in great shape, I can handle the rest!

**Comment by LiivaneLord** [comment]
I really like your calendar card. The default Home Assistant calendar is quite limited in both features and appearance. I've tried a couple of other custom calendar cards as well, but yours is by far the best-looking one.

The only thing that bothers me a little is that when adding or editing an event, it's very easy to accidentally click outside the dialog. When that happens, the dialog closes immediately and all the entered information is lost. I think it would be better if the dialog could only be closed by clicking the X, which would make accidental data loss much less likely.

Fortunately, this isn't a big issue for me personally because I don't usually create calendar events manually. My Home Assistant automations create them automatically, and I only occasionally delete or modify them by hand.

**Comment by superdingo101** [comment]
Thank you for the compliments! I don't create events in this calendar actually, I usually create them in my linked calendars which gets imported. I didn't notice the dialogue close issue. Would you mind opening a GitHub issue on the topic so I can work it when I have a chance?

**Comment by superdingo101** [comment]
Nevermind, I see it in 482. I will work on it!
